import bottleneck from "./images/article-images/bottleneck.png";
import van from "./images/article-images/van-life-crime.webp";
import pareto from "./images/article-images/pareto.gif";
import Dee from "./images/article-images/Dee.jpg";
let WaldenPondNote =
  "* The following is an excerpt from the book I’m currently writing titled Walden Pond or Central Park. This book explores themes of simplicity and transcendentalism in the information age. This piece may be incoherent without the context in the rest of the book, but I hope you can enjoy it nonetheless.";

let articleList = [
  {
    title: "Simplicity is a Bottleneck",
    note: WaldenPondNote,
    paragraphs: [
      "Are people exaggerating, deceiving, or otherwise being delusional when they say that minimalism changed their life? It seems unlikely from the outside that changing the space a person lives in, or the way they go about their life, could have an impact on the real, core personality and characteristics of that person. For many, the merits of something like minimalism are only visible through practice. Like meditation, spirituality, and other types of eye-roll inducing new age pillars, practitioners ask the public for a leap of faith when trying to change their minds. Perhaps the best way to consider problems like this is with analogy, which can remove context and bias in order to get at the core of something. Luckily for us an analogy for minimalism exists in the world of biology – the Bottleneck Effect.",
      "The Bottleneck Effect describes the change which happens to a population (of animals, fungi, bacteria, whatever) after a sudden and disruptive change happens in their environment. To illustrate this phenomenon in a simple way, let’s imagine that there is a dog pound on an island somewhere in the Pacific Ocean. The dog pound has all types of dogs, including everything from pit bulls to chihuahuas to shih tzus. One day, a volcano erupts on the island, and lava is pouring down towards the pound. In a panic, islanders take the dogs from the pound and board them onto several ships which head to nearby islands, each only large enough to house a fraction of the total number of dogs. By chance, one of the boats fills with only chihuahuas, and heads to an island which is an hour boat ride away.",
      "On this new island, populated by only chihuahuas, every new generation of dog born will look like a chihuahua. Everything dog on this new island will be small, yappy, and soft. Even though these dog’s ancestors come from a much larger genetic pool, the bottleneck effect which their lineage experienced (the volcanic eruption) shrunk the variability in genetic possibilities for these dogs. Extrapolating this to the real world, the bottleneck effect is a big part of why species differ over time. In many cases the products of bottleneck events are populations that are appear to be entirely different than the populations that their ancestors. ",
      "image",
      "With that in mind, consider what the stated function of minimalism and simplicity movements. They serve as a self-imposed bottleneck which selects for things that are essential and meaningful. Rather than a volcano randomly selecting which traits make it to the future, minimalism selects for things which are meaningful. Things which are excessive and frivolous don’t make it through the bottleneck, which allows the meaningful things to blossom on the other end. When people reduce the size of their living space, the number of things they have to tend to, or the number of hours they spend at jobs they don’t enjoy, they have created a bottleneck that has removed a lot of junk in the population that is their daily life. Over time, new things fill the void left by the cutting out of things that aren’t essential. If one is careful about selecting based on meaning, time spent on cleaning their house that is too big can be used for something like meditation. These changes pile up over time, and, like a population that looks and feels incredibly different from before the Bottleneck event, a person can go through drastic changes as well. "
    ],
    image: bottleneck,
    category: "Debt / Inequality"
  },
  {
    title: "NIMBYism",
    note: WaldenPondNote,
    paragraphs: [
      "image",
      "Zack Griffin had a dream to be a professional skier. In his early 20s he felt that if he really wanted to pursue this passion, he would have to make some drastic changes in lifestyle and priorities. He opted for a risk. He moved into a motorhome, headed west, and took a minimum wage job where he could spend the rest of his time skiing. Nearly a decade later, after slowly building credentials, the gamble paid off and he became a full-time professional skier. To accommodate his transient and frugal lifestyle during this period, he built a 112 square foot tiny home which he was able to tow from mountain to mountain. With rent costs out of the way and no requirements for a fixed location, Zack was able to spend more time on the slopes and on whichever mountain he felt would be best at the time. ",
      "Zack’s tiny home garnered a lot of attention, and he quickly realized that the niche situation which he had designed the home for could be exported to many other people that were looking for something similar in their lives. As his skiing career waned, he started a company designing and building tiny homes. The company helped people that needed cheap, mobile, and comfortable housing which was comfortable enough to live in for long periods of time. After years of helping people escape their mortgages and give them flexibility, in 2016 Zack gave a TedX talk in which he laid out succinctly exactly why tiny houses work, “How many people work in jobs that you don’t feel completely inspired by, or maybe have had a dream that just felt a bit out of reach, or maybe you feel like you just don’t have enough time for yourself or your family? Because for those of us who live in tiny houses, the definition of a tiny house may be a home under 400 square feet, but how we see it is a tool to live a life that we choose. It’s a tool that we use to avoid the financial traps that leave so many people treading water. And once you put your need for space up against your need to achieve your dreams, the actual relevance of a tiny house becomes apparent.” ",
      "Zack now stars in a Netflix series called Tiny House Nation which follows him around the country as he builds tiny houses for couples and families. He is featured as the Moses of housing, guiding people out of the servitude of expensive mortgages and suffocating rent prices to a promise land of affordability and peace. Sure, the show is a little gimmicky, as such productions for general audiences are bound to be. They skip the antecedent to many of the client’s choice to select a tiny house, which is presumably a midnight screaming and crying bout over past due mortgages and frantic prayer for an easy way out of the hell which has consumed them. But it is a charming show, and Zack is genuinely confident that tiny houses can be a way forward and scale to fit the needs of the general population. He is convinced that this house style isn’t just an oddity in the history of architecture, saying, “The tiny house movement isn’t a fad based upon an infatuation with everything small. The tiny house movement is a response to these growing environmental factors that are only going to become more and more extreme in years to come. Many people are looking at these tiny homes as ways to address these new realities.”",
      "Over his years of work of helping people build something which often has such a profound impact on their lives, he has been discouraged to learn about the reception of tiny houses by the public. The people who live in tiny houses, and the droves of people who are utterly fascinated by them, absolutely love this movement. The unwelcome reception has instead come from the NIMBY, or Not in My Backyard, crowd, which puts up a strong and active resistance to having anything untraditional near their living space. This unofficial group encapsulates the housing boards, snooty neighbors, and property managers fearful of their investments which erect barriers to different styles of homes in their neighborhoods. ",
      "Zack stumbled upon a tool which can help people live their best lives, and not only has to do the hard job of convincing people that this could work for them, but then has to enter the bureaucratic nightmare of zoning regulations and city ordinances. It’s like winning the jackpot at a casino, only to have an earthquake impede your way out the door with your loot. Zack explains, “The hardest part about living in a tiny home is not how you pair down your shoe collection. Contrary to popular belief, the hardest part is navigating building codes and zoning requirements that really limit their creation.”",
      "For most of the stories in this book, the characters only have to deal with the downward gaze of polite society. They have to deal with snide remarks and an ostracizing attitude, which sucks, but can be brushed aside by stronger people. Housing alternatives come with a higher social price tag. The NIMBY crowd see their house are their store of wealth and largest asset and seeing someone nearby in a dwelling that’s cheaper (read better) scares and offends them. They protect their home values by lobbying local housing departments to enact ordinances for minimum housing size requirements, and other varieties red tape which severely hampers tiny home construction and parking. ",
      "In his book The Small House Book, Jay Shafer (a friend of Dee Williams who inspired her to build her tiny house) enumerates many of the hurdles which stand in the way of having a tiny house in a populated area. For starters, this kind of thing is only a concern in urban or suburban environments, rural locations rarely have stipulations preventing tiny homes, and many people in tiny homes choose to live further away from cities just to avoid the burden of zoning conflicts. According to Jay, the push for big houses as a norm and zoning requirements began in the 1970s and 1980s when the housing industry and banks wanted to find ways to make more profit per structure (10). These industries pushed for regulations setting minimum-size standards, and their stated purpose was to “preserve the high quality of living enjoyed in urban and suburban areas”.",
      "Now that these standards have solidified over time, changing them or living with them can be an uphill battle. Codes vary widely based on location, but solutions often revolve around finding loopholes, such as viewing your house as a “care-taker” home for a person who’s yard you may live in. The other option is to work within the system to enact change. Jay encourages people to work with housing departments, and to treat local officials as the helpful resource they want to be rather than an adversary. Showing them evidence of how much less wasteful a tiny house is, or that property values often go up rather than down when featured in a neighborhood (11) can sway officials to work to allow tiny homes in their districts. In some cases, these disputes have made their way through the court system, and several U.S. courts have found minimum-size standards to be unconstitutional. ",
      "Changes to allow for new housing solutions have to start with the public’s acceptance of a problem with the way things are. No one is calling for an upheaval and seizure of land or telling people they can’t live in a monster house if they so choose. But, minimum size standards for homes and the requirement of taking on a large debt burden to live in a comfortable house is precluding people like Zack and Jay from getting a larger segment of the population housing which works for them. Housing can be more mobile, vastly cheaper, and less wasteful if we just allow a little more experimentation. "
    ],
    image: van,
    category: "Housing"
  },
  {
    title: "Career Strategies for Creatives",
    note: WaldenPondNote,
    paragraphs: [
      "Have you heard of the Pareto Distribution? Or maybe one of its synonyms like the 80-20 rule or the Matthew Principle? It’s a term coined by Italian civil engineer and economist Vilfredo Pareto to describe distributions which are exponential (5). A popular example, which has been discussed in detail in this book, is wealth inequality. If you mapped out every person in the US from smallest total assets ($0) to the largest amount of assets (Jeff Bezos at $161 billion), you wouldn’t see a straight line. Instead, there would be long tail with a sudden and sharp incline near the very end of the graph. Winner-take-all graphs like this are described as Pareto distributions, and this type of layout can be seen in all sorts of things from patterns in geophysics to plotting productivity for every employee at a large company.",
      "image",
      "This pattern is found ubiquitously when looking at success in creative fields. Think of Spotify streams for musicians as an example. Ed Sheeran’s “Shape of You” has a whopping 2.5 billion streams, yielding him royalty check of close to 11 million dollars for a single song. Contrast this to the average song on Spotify. Anyone can put a song on Spotify, and most of them have less than one hundred listens, which will give the artist almost to no money. Even very talented and creative artists have a very hard time getting by on their craft. It takes 336,169 streams per month on Spotify to even make minimum wage (6). This means that to ‘make it’, even modestly defining the term, requires commanding over a million minutes of human attention every month. How many people can realistically do that?",
      "The number of people who are successful in any creative field is vastly outweighed by the number of people who are creative or have talent in that field. For the vast majority of creative people the massive payday isn’t going to happen. The problem is, they can’t just stop looking at the world in a different way and choose a more ‘normal’ path in life. Their art isn’t something that can just be ignored or suppressed without major consequences, but pursuing their art has a very good chance of putting them in a position where they can’t pay the bills. It’s a hell of a catch-22. Psychologist Jordan Peterson explains in his lectures at University of Toronto that creative people, “don’t really have much choice in it. Because, if you are a creative person, it’s like a fruit tree which is bearing fruit. You can suppress it but it’s bad for you. For the creative people I’ve worked with if they’re not creative they’re miserable, so they have to do it. And there is real joy and pleasure in it, and psychological utility. But that certainly doesn’t mean it’s a conservative strategy for moving through life.” He goes on to give some advice to the aforementioned group, saying “if you happen to be creative… find a way to make money, and then practice your craft on the side, because you will starve to death otherwise. Now for some of you that won’t be true, but it’s a tiny minority” (7).",
      "Building a Walden Pond is helpful for people in many life situations. We’ve talked about its utility for people who are overextended with excessive working hours and material possessions, and for those who need to break the routine and homogenization of their life to build something that helps them reach a more spiritual connection with the world around them. But for creatives, a strategy like FIRE which can help remove them from the hamster wheel of traditional work schedules can save them from the depression and existential angst that comes with not following their passions. At the same time, it helps them pursue what their heart desires without being completely reliant on the unlikely odds of massive immediate success. A songwriter who has FIREd, lives in a paid off house, lives a simple lifestyle, and is able weather a financial storm, is more likely to keep to their craft and write for nothing but their own relation to the muse. How much art would be better if the artist wasn’t reliant on whether or not it would be sold? Would some artists be better off if they weren’t drained by the mental strain of being near starvation?",
      "Solutions for this problem aren’t going to come from exogenous sources any time soon. People who have an urge or a calling to work on something which is novel and unique will have to figure out which constellation of escape plans will work for them. Strategies like FIRE are more likely to be taken up by creative people for this reason, as they are looking for a way in which they can have the time and energy to pursue what is actually meaningful without being completely tied to the result of that endeavor. They need Walden Ponds to get their ideas onto the page, or the canvas, or in front of a VC. Our current all-or-nothing system requires starving artists and a few which are eccentric billionaires. Maybe we should emphasize strategies to reduce the plight of the former to increase the number of the later."
    ],
    image: pareto,
    category: "Work"
  },
  {
    title: "What Happens When You Stop Caring About Things",
    note: WaldenPondNote,
    paragraphs: [
      "As consumer debt climbs and working life accelerates, strategies for how to cut back on material obligations have been entering the mainstream. One of the best examples of this homeostatic mechanism in action is the 2015 documentary titled Minimalism. The film features a millennial best-friend duo who have spent their lives evangelizing the movement which shares the same name. The stars are two midwestern men in their thirties: Joshua Fields Millburn, who is tall and eloquent, and Ryan Nicodemus, who sports longish brown hair and has a more affable feel to him. They have the confidence of someone who successfully pulled off a bank heist; an Ohioan ‘awe-shucks’ persona which signals their surprise at the success of their endeavors. They come across surprisingly endearing for a film so critical to the way most American’s live. After all, their main point is that people can be happier if they cut back on how many things they own and commit their time to things which are meaningful. It’s simple and incredibly powerful.  ",
      "Anecdotally, I know a lot of people who dig their message. It resonates well with younger people, because it empathizes with the uphill battle which faces younger generations. For many, trying to keep within the straight and narrow confines of building a life of luxury through corporate work is exhausting. When some people hear the ideas laid out in Minimalism, it offers hope that there are other ways to live. And it doesn’t require more debt or overwork, it just requires people to be more deliberate in how they consume and how they work. ",
      "In the Minimalist’s book Everything that Remains, the authors describe a life of accumulation and overwork as an escape from the poverty in which they grew up. One of the authors, Joshua, spent his twenties overworking to a crippling degree. He could feel his life coming apart at the seams and was already feeling some health consequences from the stress his lifestyle required. Suspiciously, what he didn’t feel was the sense that anything he was doing was wrong. In fact, he only got pushback when he decided he needed to make a change. He cut back on spending, his time at the office, and the number of things he owned, and it was the positive changes in his life which drew concern from his peers. He recalls his experience of looking up at those ‘ahead’ of him on the journey to the C-suite, and his subsequent desire for a different life, saying: ",
      "“Don’t get me wrong, they aren’t bad people, but their careers have changed them, altered them physically and emotionally: they explode with anger over insignificant inconveniences; they are overweight and out of shape; they scowl with furrowed brows and complain constantly as if the world is conspiring against them, or they feign sham optimism which fools no one; they are on their second or third or fourth(!) marriages; and they almost all seem lonely. Utterly alone in a sea of yes-men and women. Don’t even get me started on their health issues.”",
      "This description can sound familiar to anyone who has spent energy advancing their career in a large corporation. And sure, this is a generalization, and notable exceptions exist. Elon Musk seems happy, right? But the point Joshua is alluding to is that these people aren’t winners in a competition that has yielded them the privilege of power within some section of industry – they’re prisoners. Their situation is nothing to be envied because in reality they’ve traded things much more important to get it; notably their life, health, and time. They could just walk away at any point, but two things hold people back from doing so; prestige and possessions.",
      "Joshua learned to break out of these twin holds. As he entered his 30s he made radical changes in his life such as quitting his high paying job, getting rid of his T.V. and home internet, downsizing from a large house to a cheaper and smaller apartment, removing everything from his house that he hadn’t used in the past 90 days (which he calls the 90 day rule – removing everything that hadn’t been used in the last 90 days and will not be used in the next 90), and a myriad of other things to ensure everything in his life had a purpose. The things he removed in his life freed up space for him to write for extended periods of time, and he started a now wildly successful blog and podcast with his co-author Ryan Nicodemus. Today they have a podcast and tour across the country and help others with starting the same journey that freed up their lives so much.",
      "Joshua and Ryan have inspired hordes of people to shift their focus from accumulation to appreciation. There is no silver bullet in which they provide a step-by-step guide to ‘becoming a Minimalist’, rather they write and talk about an un-ordered list of ideas and practices which can get someone a little bit closer to having a life with a little less bullshit in it. Over time readers and listeners report large shifts in their career and personal goals, more time to pursue things that interest them, better moments shared with family and friends, and an overall more fulfilling life. ",
      "Understandably, the Minimalists face a lot of skepticism when talking about how much better things can be when priorities shift. When the flaws in our behavior are pointed out, the natural reaction is often a rationalization of our behavior rather than an honest look at what was exposed. This impulse can be even stronger for someone who is intelligent, because being intelligent does not grant a person the wisdom to question their ways, it gives them the ability to rationalize their ways more soundly. But the thing that gets people into a trap in life, and the thing that can bring them out is momentum. The Minimalists often write blog posts about easy steps that can start someone on the path to getting rid of junk drawers, or just-in-case items, as an attempt to build momentum. Once a process like that starts, and momentum shifts, over time an entire attitude towards how someone interacts with the world can change. Eventually, people can’t imagine how they lived before hand, as Joshua reflected, “But when you do take that first jump, it actually becomes terrifying to do ‘normal’ things, because you realize what a risk it is to give up your entire life just to be normal.”",
      "What entices people about Minimalism, and why the idea is Transcendentalist, isn’t necessarily the freedom that comes with having less material possessions to worry about, it’s about the time it affords people to pursue what actually is important to them. Many people who are into this message are creative types, which is unsurprising because openness to new ideas (like Minimalism) and creativity go hand in hand, who find the idea of more time to create appealing. These types of people read Minimalist blogs and not only daydream about working less and having less material weight on their shoulders, but about the time they could free up in their lives to enact the ideas in their head. It’s harder to write a book when you’re working 50 hours a week to maintain your lifestyle. It’s harder to record an album when your money is headed towards mortgage payments. ",
      "The Minimalists and Emerson write because they removed all the excesses from their life and took an honest look at what was left, which was their passions and necessities. Rather than building a personality by accumulation of things and accomplishments, they built one through creation and living a lifestyle in accordance with their beliefs. "
    ],
    category: "Debt / Inequality"
  },
  {
    title: "Tiny Houses",
    note: WaldenPondNote,
    paragraphs: [
      "It doesn’t initially sound appealing to wake up with your face just a few feet from a skylight window, but it would have its advantages. It would be harder to waste the day sleeping. It would be gratifying to wake up to the milky way above if you woke up in a cold sweat. Dee Williams pondered these types of things in the waiting room of a cardiologist’s in Portland, Oregon around 2002. She was glossing over a magazine which featured a tiny home, a new concept to her, built by Jay Shafer. Soon after tiny house discovery, she was diagnosed with a chronic heart condition which would put the rest of her life in a precarious situation. The prognosis wasn’t great and left her an ambiguous amount of many good years of life she had left. Any cardiac mishap on a random day could lead to a hospice or in the care of a friend. She thought to herself that she had to build a tiny house like the one Jay had, because she didn’t know what the future held for her. ",
      "Fast forward to almost two decades later, Dee is still capable and healthy, and has become an advocate and leading voice in the ‘tiny house movement’. She has also found answers to those thoughts about skylights she wondered about in the waiting room. On a chilly day in the pacific north west, where her tiny home is parked, she wakes up to a unique frost pattern on the skylight above. Dee describes waking up to this every morning in her book The Big Tiny, saying “The fact is, even after all these years of sleeping with my head inches from the roof, of rolling over day after day to see what’s outside the skylight or on the skylight, after all this time and even though my dog has heard it all before, nature still surprises. And I’m surprised by my surprise, thinking that, at this stage of the game, I should be a bit bored by things like frost.” (9)",
      "At the time Dee decided to embark on her tiny home journey, she was in her mid-thirties. Dee is a petite blonde with an athletic build, and a charming personality which draws people into her life. She also possesses a caring attitude and a willingness to help which keeps people there. After her diagnosis she wanted to meet the man she had read about in the magazine in person, as well as see his home, Tumbleweed, for herself. She flew out to Iowa City and went with her brother, Doug, to find the home standing amongst more stationary houses in a suburb of the city. When Dee saw the house in person, the small, towable, wooden home sparked a youthful enthusiasm in her that could not be subdued or brushed aside. After entering the home and talking with Jay for a few hours at his fold out dining table, she began designing, and then building, what would be her very own tiny home. ",
      "The process wasn’t easy, and required long weekend hours, diligent study of construction ‘how to’ books, and the enlisting of her wide range of friends in the Pacific Northwest area. But when it was finished her life changed completely. The structure was only a few hundred square feet of space, but managed to feature a sleeping loft, a kitchen, a living area, and a bathroom. The exterior was furnished with beautiful hundred-year-old recycled wood from the area. The interior had a cabin feel decorated with selective tools and art which gave her and her dog RoDee a special feeling of home. ",
      "image",
      "After Dee completed work on the tiny home, she was able to sell the house that she owned and then park her new tiny home at a friend’s yard in Olympia, Washington. The freedom from mortgage payments, property taxes, and the labor required from upkeep allowed Dee to negotiate with her job to only work part-time. The rest of the time she gets to spend with her friends, dogs, and out in nature where she likes to be. The time has afforded her an opportunity to be a staple of the community around her, a go-to person whom people rely on when they need help on something and only have a cold beer and a smile to offer in return. It gave her time to write, to speak at conferences about her journey, and to help others. ",
      "At the end of the day, living in a tiny house really isn’t as radical as reality tv would have you believe. What is radical is the American perception of how much space is necessary. Humans are an incredibly adaptable species, and for much of our history, housing was neither permanent nor particularly comfortable. Even looking back 70 years ago, in 1950 the average size of a home for a family of four was 990 square feet, while today it’s 2,500 square feet. So, getting into a tiny house might be less of a mental transition than popular belief would hold.",
      "The fascination with Tiny Houses really comes down to bucking a trend which the American society is caught up in, but most people didn’t ask for. In the 1920s, Herbert Hoover lobbied builders, bankers, and relators to increase the suburban sprawl which would give each individual household more and more space. It turns out to be a profitable endeavor to furnish each American household with a small arsenal of utilities which were allotted to communities in the past. Washers and Dryers, home entertainment rooms, pools, even theaters are not unheard of in homes, and having this many resource in a location designated for just a few people is historically unusual. It can be seen as a sign of progress that the industrial capabilities of the modern age have led to this level of comfort for each nuclear familiar, but are we really to believe that this wouldn’t come with downsides? Modern convivences come with environmental degradation, social isolation, and a time and financial burden which cannot be sustained or exported in the long term.",
      "Dee and people who live in spaces like this are trail blazers looking to get us back on track to what a community should look like. If we want to have a future where people are less wasteful, more connected, and less strained by their financial obligations, then what qualifies as a ‘standard’ home should more closely resemble Dee’s than a McMansion 30 minutes outside of a major city center. Unfortunately for those of us who see the problem clearly, there is a hundred years of momentum in the law and the culture which has to be reversed in order to make spaces like this more ubiquitous. "
    ],
    image: Dee,
    category: "Housing"
  },
  {
    title: "Calculating Your Real Wage",
    note: WaldenPondNote,
    paragraphs: [
      "Vicki Robin has been writing and speaking about FIRE for the better part of three decades. She is 75 and lives in a tiny place just north of Seattle on Whidbey island (why do all of our protagonists live in the Pacific Northwest?). She has a passion, or maybe an obligation, for teaching people how to step off the 9-5 treadmill. In her book Your Money or Your Life, she outlines a program which can help people form a different relationship with money. Essentially, her goal is to get people to see money as a trade for “life energy” (6). ",
      "The term isn’t as woo-woo as it sounds – she literally has you calculate how much time you have remaining in your life (a morbid thing to estimate) and consider how much of that time remaining you are willing to trade for currency. Every time you make a transaction from a purchase of a nice meal or food for the hungry, you are essentially dipping into that bank of time remaining on this planet in exchange for that purchase. This sounds dramatic, but this idea starts to feel more logical when you start to consider the required time to accumulate the money required for every purchase. The book is essentially runs through a step by step guide to help the reader get better at tracking life energy and consider how it is used in order to maximize whatever is left in the bank. In her experience, when people start to make these calculations, they tend to spend less time at work selling their life energy, and less of their life energy on things that aren’t contributing much to their health and happiness.",
      "One of the more profound steps in this book is one that asks people to calculate their ‘real wage’. How much money you earn from working is more than just the bottom line that you sign in your employee agreement. What you take home from work is garnished by some factors which are not immediately visible. An obvious one would be commuting; if you spend 1.5 hours each day on a commute, then at the end of the week your paycheck is not ‘$x’ for 40 hours of work, it’s already up to 47.5 (1.5 hours each day x 5 days a week). This means if you think you’re paid $25 and hour and not considering any externalities about the job, when you factor in commuting, you’re actually being paid $21.5 an hour. Also, think of the laundry list of things people spend money on outside of work because they hate their time at their job and need to cope. Alcohol, cocaine, and all-inclusive resorts come to mind. These material comforts required to get a person back to baseline once they’ve returned from an exhausting day or week are externalities which are not originally accounted for when thinking about a basic view of wage. Vicki writes about these costs saying, “Be prepared to discover how much you spend with ‘I hate my job’ as the underlying reason”. She has a more extensive list which goes into further detail for finding out how much money you actually earn per hour. Below are the things she recommends considering, and in addition an estimate of how much time and money each of these items could be costing:",
      "1.	Commuting: as mentioned above, many people spend an unexpectedly high cost for their transportation to work. In addition to the time it takes, factor in costs like car payments, subway passes, or toll payments that are only necessary because of a daily commute. 7.5 hours / week, $100/ week",
      "2.	Costuming: As Vicki puts it, “Are the clothes you wear at work the same ones you wear on your days off or on vacations?” If your work requires a certain look, and that comes out of your pocket, then it’s another thing which needs to be subtracted from take home pay. 1.5 hours / week, $25 / week",
      "3.	Meals: This includes things like morning coffees and meals ordered because of a busy work schedule and the inability to make these rather than purchase them. 5 hours/week, $50 / week",
      "4.	Daily Decompression: If it takes time to ‘return to baseline’ after a long day’s work, then that time spent is a job-related expense. If it requires entertainment or substances to facilitate that process, that is also an expense that wouldn’t be necessary without the job in question. 5 hours/week, $30 / week",
      "5.	Escape Entertainment: Things like a night out at bars and restaurants because of the need to ‘blow off some steam’. Time and money spent trying to get away from the stress of employment and find thrill or meaning because so much of the week is devoid of these things. 5 hours/week, $40 / week",
      "6.	Vacations: There is a distinction to be made here between travel as a life enhancing experience (which can open your eyes to new cultures and broaden your understanding of the world), and a ‘vacation’ that looks more like getting wasted on a cruise deck while making frequent stops at a buffet on a floating city which in circles between ports at Caribbean islands. If the travel looks more like the later than the former then it’s a job-related expense, because that sedimentary outing is more of a “get-away” to escape the troubles of working life. 5 hours/week, $30 / week",
      "7.	Job-Related Illness: A stressful working life can have a real impact on living a healthy life. Heart health, back and joint pain, and immune system health can be compromised by working a shitty job. Those health deteriorations are a cost as well in the form of health care costs and the reduction of good days left in one’s life. 1 hours/week, $25 / week",
      "8.	Other: Anything else that cannot be taken care of personally because of your job. Housekeepers, dog sitters, day cares, handymen, or any other cost that is exported because of the lack of time to tend to it. 5 hours/week",
      "Let’s think back and consider our hypothetical 40 hours for $1000 a week job example (or $25 an hour) from earlier. If we calculate a real wage for this job using the costs associated with all of the factors above, then that job would actually be 70 hours a week for $700. Under the premise of real wage being an accurate figure for representing all of the externalities which go into working a job, this gig would go from $25/ hour as the number written on the employee agreement to just $10 an hour when all factors are included. $10 an hour before taxes might not be worth the time commitment when things are all said and done. Now this is obviously just an example, and having a job with a laid-back dress code, close to home, that doesn’t add much stress would put the real wage earned far closer to the traditional wage. But, that’s exactly the point of doing a calculation like this. There are so many factors that are taken for granted in the modern working environment, and without sitting down and going through the actual implications of taking on a specific job, it’s easy to be blissfully unaware of just how much life energy is being syphoned away at a place of employment. ",
      "Consider the flip side of this too after calculating your real wage. Referring to the breakdown above, Robin says, “In this example, every dollar you spend represents 6 minutes of your life. Think of that every time you shell out yet another $20…Ask: Is this item worth 120 minutes of my life energy? Is it worth the two hours of sitting in traffic, driving to work, or hunting down future clients?” If there is a better argument for frugality than that, I’ve yet to hear it. "
    ],
    category: "Work"
  },
  {
    title: "Emerging Educators",
    note: WaldenPondNote,
    paragraphs: [
      "In terms of influence, the greatest history teacher who ever lived is a former news reporter that lives in Eugene, Oregon. He lives a simple life with his family in Oregon and spends most days researching lesser known historical events and recording his thoughts about them. Every 6 months or so, he weaves grand narratives from this research into recordings that span across multiple part series which are hours long each. His storytelling is masterful, bringing together engaging narratives and important historical facts into a beautiful synthesis. When this process is complete it gives a listener not only a new perspective on the past in a way that makes people more seriously consider their present, but also an insight into deep philosophical questions. Though he is a history teacher for millions, he probably wouldn’t be recognized walking down the street – unless he spoke. His name is Dan Carlin and he does this all through a podcast called Hardcore History. It’s a free product and it attracts millions of listeners every year. The podcast is known to be long, entertaining and thought provoking, but rarely does the gravity of what is going on with these episodes get discussed. He is making history accessible to the general public in a way that is incomparable to any other teaching strategy in human history. Rather than person to person, or person to page to person, Hardcore History, and podcasts like it, give a person to person teaching experience which is digitalized, copied, and disseminated an unlimited amount of times with an unprecedented level of accessibility. ",
      "When Dan started Hardcore History in 2006, he was completely unsure of what it could lead to. When podcasts were just blossoming, their potential seemed distant and vague. During the beginning days of the show, Dan focused on obscure history questions of the sort that would occupy a conversation over coffee for a group of history nerds. Examples of early topics included questions like ‘was Alexander the Great worse than Hitler?’ or ‘what if the year 1066 had gone differently?’. The show evolved when early listeners said they needed more context to what Dan was talking about in the first place, and then the length of the show swelled to accommodate that direction. The show’s audience grew and so did the depth of what it covered, and no longer was the show aimed around easily packaged questions like ‘was Alexander the Great worse than Hitler?’ it was becoming a grand narrative about the people like Alexander the Great’s life, his ancestors, and his conquests, all so that the listener could answer questions like that for themselves. In 2015, almost 10 years after its debut, Hardcore History released Blueprint for Armageddon VI, which is a 4-hour story about the end of the first World War. It got 350,000 downloads in the first day.",
      "Even at a university where people are hungry for information and are paying top dollar for an education, it would be impossible to get that number of people to sit through a 4-hour lecture about a six-month period during WW1. Imagine trying to fill over 3 Michigan stadiums full of people to sit and listen to a person describe a period in time between 1917 and 1918. It’s absurd, and yet Hardcore History consistently has that kind of reach. The university system is a great way to provide in-depth information to a small group of people, but for a lot of student’s education they are required to focus on topics that help them get jobs rather than ones that might be outside the purview of the education to employment pipeline. Hardcore History shows that people are craving knowledge that falls outside of their domain of their career or education. Plus, the format of a podcast is more accessible than a book because people can listen to them while doing daily routines like driving or chores. In essence, listeners are filling their otherwise mundane hours of the day with lessons that are on par with university courses which students would have to pay thousands of dollars for. The difference is that podcasts listeners are doing it out of choice and pure enjoyment out of the topic their listening to, while university courses often feature snoozing students because their audience is attending that lesson for a credential rather than the information itself. ",
      "Podcasts, and forms of media like them, break down barriers that used to exist between information and people. They have given tools directly to the people to build their own understanding of the world, and that idea is deeply in step with what the Transcendentalists advocated for. It’s a matter of building self-reliance rather than institutional reliance. In a Transcendentalist view, people are better off when we aren’t dependent on gatekeepers to shepherd us through the learning process, but when we can build our experience and knowledge directly to answer questions that puzzle us on a deeper level. If Dan Carlin was a history teacher at some high school or college in Oregon, his impact would be a miniscule fraction of what it is today. He chose not to tether his work to any institution, but to make it free and available, and as a result millions of people have benefited from an understanding of history which helps them make sense of their place in the world.",
      "This phenomenon goes beyond history podcasts, and most of the information you could ever want to know about can be found online through a podcast, an audiobook, or a YouTube lecture series. For those who are curious about the world this is an absolute game changer.  The University system is no longer the only game in town for educating the masses, and in many cases it’s an inferior mechanism. The advantage that the University system has now over self-directed learning is accreditation. Over time, though, how much will something like a Bachelor’s in Communication mean to employers if the person who obtained it isn’t actually skilled or knowledgeable? It seems that in many cases certificates of education are not an accurate proxy for telling whether or not someone is competent. They still are for topflight schools, but how about lower or middle-tier universities which still carry the same price tag? I don’t think I’m alone in recognizing that some of the people I’ve met with college degrees don’t exactly classify as intellectual heavy weights. Emerging jobs in the Information Age require knowledge workers, not cogs in a machine that can repeat tasks. The self-directed learning route signals for people who get skilled at seeking out their own information and are curious, and these are often people who can synthesize ideas from disparate fields into ways that a computer is unable to. The university route, on the other hand, can too often privilege memorization of facts about a topic crammed into a small timeframe, and signals for people who have something closer to grit than wisdom or intellect.  ",
      "Before I sound like I want to tear down the educational institutions of America, let me say it’s true universities can be extremely beneficial for many people. A liberal arts degree can make people into better critical thinkers, expose them to new ideas, allow them to develop/find themselves, and give people the social resources to succeed. But it is not the only way to do those things, and it’s time to stop acting like a college degree should be the standard approach. Many 18-year old’s don’t know what they want to do with their lives, and for some of them it could be a better idea to: work and travel the world, listening to experts online rather than in the classroom, learn about different cultures, and read widely along the way. For many, I suspect this is a better way to understand the world and yourself than going into thousands of dollars of debt to find some direction. As more people follow the Dan Carlin blueprint, the wealth and quality of information that is accessible without a paying absurd tuition price will change the landscape for learning. "
    ],
    category: "Education"
  },
  {
    title: "Taking Education Personally",
    note: WaldenPondNote,
    paragraphs: [
      "Tim Ferriss is a person famous for a lot of things. Some know him from his books like the 4-hour workweek, others from his massive podcast The Tim Ferris Show, and a smaller portion from his investment and mentoring in Silicon Valley startups. He is a self-described ‘human guinea-pig’, and he makes a living questioning conventional thought to find a more efficient way to achieve similar or improved outcomes. These days Tim lives in Austin, Texas, writing books, recording podcasts with experts on a wide range of topics, and just generally being an oddball and contrarian. It cannot be surprising, then, that a person like this has a lot to say about education. Education at every level is begging for innovation and improvement, as evidenced by the thousands of dollars parents will pay to get their children into Montessori schools or the raging debates over student debt and the daunting job market which confronts new graduates. Tim had his own schemes and takes on primary school education as well as his university schooling at Princeton which we won’t go into detail here about, but his take on an MBA degree is worth focusing in on for its applicability to most people’s lives.",
      "Tim is in his 40s now, but back in his 20s he wanted to enroll in an MBA program (2). In 2005, before his entrance to mainstream success, he did his research on which programs he could get into, and which would yield him the best outcomes. Eventually he came to the conclusion that the Stanford Graduate School of Business was right for him. He then visited Stanford to sample what his $120,000 2-year program would get him, and upon arrival he was massively disappointed by the product. “Some [classes] were incredible, taught by all-stars who’d done it all”, Tim said, “but others — many others — were taught by PhD theoreticians who used big words and lots of PowerPoint slides. One teacher spent 45 minutes on slide after slide of equations that could be summed up with ‘If you build a crappy product, people won’t buy it.’ No one needed to prove that to me with differential calculus. At the end of that class, I turned to my student guide for the tour and asked him how it compared to other classes. He answered: ‘Oh, this is easily my favorite.’ That was the death of business school for me.”",
      "After leaving the campus, he had an idea for a “self-directed MBA”. His planned to take the $120,000 that would have gone to funding his education, and instead use that money to get real world experience. He posited that his experiments with that money and time would open up more doors and teach him more about the world of business than a stuffy classroom like the one he experienced ever could. Over the course of the next two years, Tim would invest that fund in small start-up companies, and learn about entrepreneurship and venture capital through the actual process of building up a company. This had the effect of dramatically shortening the feedback loop between theory and result, and instead of learning for two years about how start-up businesses worked before becoming involved he gained first-hand knowledge early and often. Embedding himself in a few start-ups gave Tim a closer look into the reality of what it took to be successful in that world. He talked with the engineers and wide-eyed businesspeople working on their products and learned from them directly about what their struggles and strategies were. The kicker is, he had considered the fund a sunk cost when he started his self-directed MBA program – but he ended up re-cooping his investment in total. Some of his investments ended up paying off, so not only did he get a better education but his upfront fee turned out to be a risk that returned capital rather than a fee which yielded a credential.",
      "Perhaps this style of experimentation and learning doesn’t apply to everyone. Tim had the benefit of knowing who to talk to and had some previous business experience before going down this rabbit hole. But, the concept of self-directed learning and experimentation is one that can be grafted onto many situations for people looking to better themselves. Taking personal responsibility for building an education brings people closer to the goal that they set for themselves than an institution is able to do. By definition, large institutions are accreditation factories for people who want to achieve an outcome that requires their blessing. They work on a general level, and they do well to provide a blanket coverage of knowledge to their students, but they cannot be specific or individualistic enough to get a person ready for a niche or unique goal they set for themselves. Tim’s career has been winding and weird, and Stanford’s MBA program could not have prepared him for the turns it has taken. On the other hand, the two years of his self-directed education provided him far more specific insights for the years to come and more skin in the game while doing it. ",
      "Extrapolating Tim’s education let’s say a person wants to be a writer. Rather than getting a Masters degree in creative writing, which will cost a lot of time and upwards of $20,000, Tim offers the approach of “join a writers’ group and negotiate Mondays off work (to focus on drafting a novel or screenplay) in exchange for a $10-15,000 salary cut.” Wouldn’t talking to other writers and having the time to create be a more targeted path for getting one’s work out there? Or how about a blossoming interest in politics. What if instead of relying on a university for knowledge, you could “dedicate one day per week to volunteering or working on a political campaign. Decide to read one book per week from the Georgetown PoliSci department’s required first-year curriculum.” Rather than offloading decisions about the future to a university which may or may not be adequate, why not take matters into your own hands? People know far more about what they are supposed to do than universities give them credit for sometimes. "
    ],
    category: "Education"
  },
  {
    title: "Deep Thought",
    note: WaldenPondNote,
    paragraphs: [
      "Standard educational models focus on convergent thinking and rote memorization, which is why their 20th century design is quickly becoming obsolete. Primary school, and often higher education, privilege processing speed over deep thought and careful deliberation. Value is placed on conformity and adherence over creativity and dissent. In the 21st century, these differences outline the growing chasm between the skills that are increasingly in demand and those which are becoming irrelevant. The ones which schools prepare children for – show up on time, move subjects when the bell rings, answer the questions in the right way, and shut up when you’re asked to – are training people to be cogs in a factory, which is work that should be left to machines anyways. Machines can repeat tasks time and time again or make a single, programmable, decision far better than any human could. Our educational models are at a disadvantage by not recognizing this dichotomy, and a micro chasm of this oversight can be seen by looking at their selection processes.",
      "Malcolm Gladwell, the famous writer and public intellectual, touches on this subject in his podcast Revisionist History.  In it, he personally undergoes one of the most well recognized and lauded higher education selection mechanisms – the Law School Admission Test or LSAT. He speaks about his experience on two episodes of his podcast titled “Puzzle Push” and “The Tortoise and the Hare” (3). The episodes meander through the design principles of the LSAT, and he speaks with experts about what the explicit function of the LSAT, and standardized tests like it, are trying to do. Eventually it is revealed that they are looking for people who can reach a good answer in a very short amount of time. They want to give the highest grades to those who have the best snap-shot judgement and who can process information quicker than their peers.",
      "But is that real intelligence? It is certainly a skill to be able to digest a ton of surface-level information in a short sitting, but often that is not even what law professionals are looking for. The job of a lawyer, judge, or law clerk is to go deep on a set of information, reading the same passages time and time again, and looking at it in a way that no one else has seen it before. It requires careful, drawn out, concentration and creativity. ",
      "As the story develops, Malcom begins to make it clear that many of the people who use the LSAT as a measure of who to let into their gated institutions are weeding out the very people which would perform the best in their environment. Because the top law schools only let in the people who perform best at the LSAT, the most important positions in the justice system or corporate lawyers are those who can synthesize large bulks of information and find the relevant details. However, it does not necessarily mean that these people are good at looking at new angles from this information or synthesizing it with disparate information. ",
      "One of the unexpected professions in the cross hairs of automation happens to be some lawyers. Because the profession of interpreting the law relies on a standard set of rules, and glossing over lots of information quickly, computers are better set to take on the some of the tasks which consume a portion of the lawyer’s time and energy. Neil Sahota investigated the future of AI in law and reported, “Currently, the legal system relies on armies of paralegals and researchers to discover, index, and process information. For law firms at present, this reliance can be expensive, driving up the rates they charge… However, for just a fraction of the time and expense, AI could be used to conduct time-consuming research, reducing the burdens on courts and legal services and accelerating the judicial process.” (4) The skills which the LSAT privileges are the ones which AI is most likely to take over. Ironically, the LSAT is selecting for the types of lawyers which are good at the tasks that are most likely to be automated in the near future. ",
      "Gladwell uses the voice of the late Antonin Scalia makes in his episode about his investigation into the LSAT, and justice Scalia is quoted saying that, “he only hires people who graduate from top law schools like Harvard”. By definition these are the people with the highest scores on the LSAT. Then, in the same breath, he mentions that his top clerk is someone who he hadn’t hired, and who went to Ohio State (and presumable scored much worse on the LSAT). The paradox is lost on him. His best law clerk is someone who does not have the skills necessary to get through the higher education selection systems. The skills his top clerk does have must then be outside of the framework of what they are looking for. ",
      "The reality of the LSAT is that it does not function as a proper selecting mechanism which allows the top prospects, for the 21st century at least, to rise to the top. It is a test which provides an easily understood bell-curve which makes the job of university administrators easier. It draws lines students up on an arbitrary skill which often privileges students on the exact opposite lines of what they should be looking for. To become the talent which is needed going forward, or to find it, it can be beneficial to take the selections mechanisms of the past with a heavy grain of salt, and think about focusing on what kind of skills are more likely to dodge the oncoming freight train of automation. "
    ]
  }
];

export default articleList;
